package com.sohai.platformer.audio

import com.badlogic.gdx.Gdx
import com.badlogic.gdx.audio.Sound
import com.badlogic.gdx.utils.Disposable

/**
 * Loads and plays all game SFX.
 *
 * Primary sounds live in audio/sfx/ (T-013 canonical set).
 * Legacy sounds in sounds/ are kept for backward compatibility.
 *
 * Usage:
 *   SoundManager.init()
 *   SoundManager.play("jump")
 *   SoundManager.play("collect_token")
 */
object SoundManager : Disposable {

    private var enabled = true
    private var volume = 0.8f
    private var uiVolume = 1f
    private val sounds = mutableMapOf<String, Sound>()

    /**
     * T-013 canonical SFX: key → path relative to the assets root.
     * These 8 files are pre-generated by ProceduralSoundGenerator (or
     * shipped as WAV files in assets/audio/sfx/).
     */
    private val sfxFiles = mapOf(
        "jump"               to "audio/sfx/jump.wav",
        "land"               to "audio/sfx/land.wav",
        "collect_token"      to "audio/sfx/collect_token.wav",
        "collect_snapshot"   to "audio/sfx/collect_snapshot.wav",
        "death"              to "audio/sfx/death.wav",
        "checkpoint"         to "audio/sfx/checkpoint.wav",
        "level_complete"     to "audio/sfx/level_complete.wav",
        "hazard_cleansed"    to "audio/sfx/hazard_cleansed.wav",
        "achievement_unlock" to "audio/sfx/achievement_unlock.wav"  // T-138
    )

    /**
     * Legacy sound keys still used by older GameScreen call-sites.
     * These fall back to the legacy sounds/ directory.
     */
    private val legacyFiles = mapOf(
        "collect"       to "sounds/collect.wav",
        "cleanse"       to "sounds/cleanse.wav",
        "ability_ebo"   to "sounds/ability_ebo.wav",
        "ability_laya"  to "sounds/ability_laya.wav"
    )

    /**
     * Initialise the sound manager.
     * Call after [ProceduralSoundGenerator.generateAll] so the WAV files exist.
     * Safe to call multiple times — subsequent calls are no-ops.
     */
    fun init() {
        if (sounds.isNotEmpty()) return

        val allFiles = sfxFiles + legacyFiles
        for ((name, path) in allFiles) {
            val handle = Gdx.files.internal(path)
            if (!handle.exists()) {
                Gdx.app.log("SoundManager", "Sound not found: $path (will be silent)")
                continue
            }
            try {
                sounds[name] = Gdx.audio.newSound(handle)
            } catch (e: Exception) {
                Gdx.app.error("SoundManager", "Failed to load: $path", e)
            }
        }
    }

    /**
     * Play a sound by name.
     *
     * T-013 canonical names: jump, land, collect_token, collect_snapshot,
     *   death, checkpoint, level_complete, hazard_cleansed
     * Legacy names: collect, cleanse, ability_ebo, ability_laya
     *
     * @param name  Sound key (see maps above)
     * @param pitch Playback pitch multiplier (default 1.0)
     */
    fun play(name: String, pitch: Float = 1f) {
        if (!enabled) return
        sounds[name]?.play(volume, pitch, 0f)
            ?: Gdx.app.error("SoundManager", "play() called for unknown sound: $name")
    }

    /** Play a UI sound using the UI bus volume configured via [setUiVolume]. */
    fun playUi(name: String, pitch: Float = 1f) {
        if (!enabled) return
        sounds[name]?.play(uiVolume, pitch, 0f)
            ?: Gdx.app.log("SoundManager", "playUi() called for unknown sound: $name")
    }

    /** Convenience overload — no extra parameters needed for one-shot SFX. */
    fun play(name: String) = play(name, 1f)

    fun setVolume(v: Float) { volume = v.coerceIn(0f, 1f) }
    fun setUiVolume(v: Float) { uiVolume = v.coerceIn(0f, 1f) }
    fun setEnabled(e: Boolean) { enabled = e }

    override fun dispose() {
        sounds.values.forEach { it.dispose() }
        sounds.clear()
    }
}
